# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

builds:
  - id: terramate
    binary: terramate
    main: ./cmd/terramate
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
  - id: terramate-ls
    binary: terramate-ls
    main: ./cmd/terramate-ls
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
archives:
  -
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

chocolateys:
  - name: 'terramate'
    ids:
      - 'terramate'
      - 'terramate-ls'
    title: Terramate
    authors: Terramate GmbH
    project_url: https://github.com/terramate-io/terramate
    icon_url: 'https://raw.githubusercontent.com/terramate-io/brand/main/whitemode/stamp.svg'
    license_url: 'https://github.com/terramate-io/terramate/blob/main/LICENSE'
    require_license_acceptance: false
    project_source_url: 'https://github.com/terramate-io/terramate'
    docs_url: 'https://github.com/terramate-io/terramate/blob/main/README.md'
    bug_tracker_url: 'https://github.com/terramate-io/terramate/issues'
    summary: 'Terramate - your infrastructure as code software'
    description: |
      Terramate helps you manage and version your infrastructure as code.
    release_notes: 'https://github.com/terramate-io/terramate/releases/tag/v{{ .Version }}'
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: 'https://push.chocolatey.org/'

dockers:
  - dockerfile: hack/release/Dockerfile
    image_templates:
      - "ghcr.io/terramate-io/{{.ProjectName}}:latest"
      - "ghcr.io/terramate-io/{{.ProjectName}}:{{.Version}}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^spec:'
      - '^test:'
      - '^tests:'
      - '^testing:'
      - '^refactor:'
      - '^chore:'

release:
  prerelease: auto

announce:
  twitter:
    enabled: false
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

  slack:
    enabled: false
    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    channel: '#terramate'
    username: 'terramate'
    icon_emoji: ':terramate-logo:'

  discord:
    enabled: true

    message_template: |
      🥳 We just released #Terramate {{.Tag}} 🚀🚀🚀
      {{ .ReleaseURL }}

    author: 'terramate'

    # Default: 'https://goreleaser.com/static/avatar.png'
    icon_url: ''
