# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

name: ci-experimental
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'makefiles/**'
      - '.github/**'
      - '**/*.tm.hcl'
      - '.tool-versions'

jobs:
  build_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: ["windows-2022"]
        go: ["1.21"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2
          tofu_wrapper: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: configure git
        run: git config --global core.autocrlf false
    
      - name: make build
        run: make build

      - name: make generate
        run: ./bin/terramate.exe generate

      - name: make test
        run: make test

      - uses: Kesin11/actions-timeline@v1
